server:
  port: 8518
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db1
    username: root
    password: 123456
#mybatis-plus
#mybatis-plus:
#  # 搜索指定包别名
#  typeAliasesPackage: com.example.demo.model
##  mapper-locations: classpath*:com/example/demo/mapper/*.xml
##  mapper-locations: classpath*:mapper/*Mapper.xml #classpath后添加你xml文件的目录
##  mapper-locations: classpath:mapper/*.xml
#  # xml
#  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔

  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      # logic-delete-field: delete_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 正常
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


## mybatis
#mybatis:
##  mapper-locations: classpath:mapper/**/*.xml
#  mapper-locations: classpath:/mapper/*Mapper.xml
##  typeAliasesPackage: com.yourpackage.*.entity
#  # 控制台打印sql语句
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  # 开启驼峰转换
#    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      id-type: auto
#    banner: true
